# Generated by Django 5.0.3 on 2024-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billreminder',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('internet', 'Internet'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('water', 'Water'), ('other', 'Other')], max_length=20),
        ),
    ]
