# Generated by Django 4.2.10 on 2024-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_income_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
